### PR TITLE
Add Chat Invites and Bans

### PR DESCRIPTION
**Pull request by showierdata9978**
Misc Changes:
Fix Type errors in alot of places with pycharm

(Redone #208)

### CODE REVIEW

**Comment by showierdata9978** [comment]
I just realised i forgot to test it lmao

**Comment by showierdata9978** [comment]
tested and fixed

**Review by MikeDev101 — APPROVED** [review]

**Comment by showierdata9978** [comment]
TODO: Allowing admins to edit chats that they do not own

**Comment by tnix100** [comment]
Btw, moved /invites out of /chats so in the future we can have other invite types if we ever need them.

**Review by tnix100 — APPROVED** [review]

**Comment by showierdata9978** [comment]
do not change the things that was required for intelligence

**Comment by showierdata9978** [comment]
.

**Pull request merged**
