### PR TITLE
dockerify & remove old files

### PR DESCRIPTION
**Pull request by williamhorning**
This PR adds support for running Meower Server using Docker Compose, making it easier to be run in setups that already use Docker. This PR also updates the readme to explain the different methods of running Meower Server and also removes the unused `meower-old` directory

### CODE REVIEW

**Review by MikeDev101 — CHANGES_REQUESTED** [review]
Should leave Proxmox as an option in the readme.

**Comment by williamhorning** [comment]
@MikeDev101 It's still listed as an option

**Review by MikeDev101 — APPROVED** [review]
LGTM after being pointed out that Proxmox is an option.

**Comment by showierdata9978** [comment]
> LGTM after being pointed out that Proxmox is an option.

LMAO

**Review by tnix100 — APPROVED** [review]

**Pull request merged**
