### PR TITLE
Add limits to group chats

### PR DESCRIPTION
**Pull request by tnix100**
Limit adding/removing members to 5 members per 3 seconds, and limit group chats to 100 members.

### CODE REVIEW

**Comment by tnix100** [comment]
Yeah, I'll make a patch for Meower Svelte later

**Comment by tnix100** [comment]
I tried a 300 member group chat on Meower Svelte, it ran completely fine. So I've raised the limit to 256 members (I asked for 250, Mike wanted to make it 256).

**Comment by showierdata9978** [comment]
Btw filewrite will be broken

**Comment by mdwalters** [comment]
btw there should be a block where the user was added two times to a chat

**Comment by tnix100** [comment]
> 

that was already implemented a long time ago

**Comment by mdwalters** [comment]
ok

**Review by MikeDev101 — APPROVED** [review]

**Comment by mdwalters** [comment]
oh no

**Comment by tnix100** [comment]
> 

He said he will deploy tomorrow when the server goes down for scheduled maintenance.

**Pull request merged**
