### PR TITLE
Listing users endpoint

### PR DESCRIPTION
**Pull request by NotFenixio**
Tested and ready to merge

### CODE REVIEW

**Comment by williamhorning** [comment]
What’s the use for this? I see a number of privacy concerns with this and I’m struggling to imagine any benefit to this

**Comment by EngineerRunner** [comment]
> @williamhorning: What’s the use for this? I see a number of privacy concerns with this and I’m struggling to imagine any benefit to this

could be useful for bots

**Comment by NotFenixio** [comment]
For example, for fetching a random user. How exactly is this a privacy concern? Deleted accounts and sensitive fields are deleted.

**Comment by williamhorning** [comment]
> could be useful for bots

how? i think that giving bots access to this would open the doors to even more chaos

**Comment by EngineerRunner** [comment]
> > @EngineerRunner: could be useful for bots
> 
> @williamhorning: how? i think that giving bots access to this would open the doors to even more chaos

what chaos, exactly? i don't see what harm could be done with it that wouldn't already be possible.

**Comment by williamhorning** [comment]
@EngineerRunner i can think of this list easily:

1. scraping the platform for information about users becomes far easier (not that it isn't extremely easy already), and this presents privacy concerns, especially with regulations like the GDPR

2. bots and other users shouldn't have information about users who don't interact with them. there's a reason other, far larger platforms, impose restrictions on what user information can be accessed by bots and users depending on their relationship to the user. additionally, no one else provides a directory of users and that's a GOOD thing.

3. if you need a list of users, i don't see why using ulist or the chat member list shouldn't be sufficient unless you need to do moderation-y tasks, which should be handled in a completely separate way

**Comment by NotFenixio** [comment]
Alright then :/

**Pull request closed without merging**
