### PR TITLE
add 🅱️

### PR DESCRIPTION
**Pull request by EngineerRunner**
:shipit: or this is 🅱️ull****

### CODE REVIEW

**Review by windynoodles — APPROVED** [review]
🅱️

**Comment by cheesewhisk2rs** [comment]
🅱️

**Comment by SoupleCodes** [comment]
🅱️

**Comment by Supernoodles99** [comment]
🅱️till 🅱️aiting 🅱️or 🅱️his 🅱️o 🅱️e 🅱️erged

**Review by sandstripes — APPROVED** [review]
i a🅱️🅱️rove of this feature

**Comment by tnix100** [comment]
🅱️orry 🅱️o 🅱️uin 🅱️veryone's 🅱️un 🅱️ut 🅱️ris 🅱️ays 🅱️o.
(sorry to ruin everyone's fun but eris says no)

**Comment by Supernoodles99** [comment]
i have been enraged

**Comment by EngineerRunner** [comment]
s🅱️rew 🅱️ou gu🅱️s

**Comment by cheesewhisk2rs** [comment]
i say 🅱️o to e🅱️is

**Pull request closed without merging**
