### PR TITLE
upgrade better profanity to updated fork

### PR DESCRIPTION
**Pull request by showierdata9978**
Better Profanity seems inactive, and i made a fix for it.

this pr is integrating that fix

### CODE REVIEW

**Comment by showierdata9978** [comment]
> [MikeDev101](https://github.com/MikeDev101) approved these changes on behalf of https://github.com/orgs/meower-media-co/teams/backend [3 hours ago](https://github.com/meower-media-co/Meower-Server/pull/109#pullrequestreview-1156481912)

merge, then?

**Comment by MikeDev101** [comment]
Would wait until Tnix sees changes. Also, changes won't be applied until the next server maintenance day, since this is a low-priority issue.

**Comment by tnix100** [comment]
What is the performance like compared to vanilla better_profanity?

**Comment by showierdata9978** [comment]
> What is the performance like compared to vanilla better_profanity?

i did not notice any difference from newest pypi version

**Comment by tnix100** [comment]
> > What is the performance like compared to vanilla better_profanity?
> 
> i did not notice any difference from newest on gh

Please run the benchmarks they provide in the better profanity repo: https://github.com/snguyenthanh/better_profanity/tree/master/benchmarking

**Comment by showierdata9978** [comment]
```
--------------------------------------------------------------------------------------------- benchmark: 9 tests --------------------------------------------------------------------------------------------
Name (time in ms)              Min                    Max                   Mean                StdDev                 Median                   IQR            Outliers     OPS            Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_1para_100per         439.5640 (1.0)         475.8678 (1.0)         447.6484 (1.0)         15.7875 (5.01)        440.7873 (1.0)          9.4385 (1.91)          1;1  2.2339 (1.0)           5           1
test_1para_50per          597.9272 (1.36)        659.5887 (1.39)        620.4577 (1.39)        25.9461 (8.23)        611.4177 (1.39)        40.1456 (8.11)          1;0  1.6117 (0.72)          5           1
test_1para_0per           733.0284 (1.67)        740.7462 (1.56)        737.2409 (1.65)         3.1529 (1.0)         736.4871 (1.67)         4.9471 (1.0)           2;0  1.3564 (0.61)          5           1
test_1para_5per           889.3416 (2.02)        909.3640 (1.91)        894.6700 (2.00)         8.2919 (2.63)        891.4575 (2.02)         6.2908 (1.27)          1;1  1.1177 (0.50)          5           1
test_10para_100per      4,946.3864 (11.25)     5,115.2026 (10.75)     5,020.2844 (11.21)       61.0389 (19.36)     5,018.7181 (11.39)       58.6670 (11.86)         2;0  0.1992 (0.09)          5           1
test_10para_5per        5,463.8858 (12.43)     5,586.0481 (11.74)     5,521.8533 (12.34)       55.1945 (17.51)     5,536.2849 (12.56)       99.9539 (20.20)         3;0  0.1811 (0.08)          5           1
test_10para_50per       5,814.2221 (13.23)     5,855.8379 (12.31)     5,838.9455 (13.04)       16.1365 (5.12)      5,841.0054 (13.25)       22.2172 (4.49)          2;0  0.1713 (0.08)          5           1
test_10para_0per        6,069.0170 (13.81)     6,145.5145 (12.91)     6,109.1628 (13.65)       28.5191 (9.05)      6,111.0401 (13.86)       37.9452 (7.67)          2;0  0.1637 (0.07)          5           1
test_100para_5per      56,823.2007 (129.27)   65,406.6388 (137.45)   60,121.8785 (134.31)   4,114.5428 (>1000.0)  57,661.9689 (130.82)   7,204.2713 (>1000.0)       1;0  0.0166 (0.01)          5           1
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

**Comment by showierdata9978** [comment]
slight decrease in speed;
@tnix100, cc @MikeDev101

**Comment by tnix100** [comment]
Alright, it is a bit of a decrease in performance but will be ok for us since we're just doing it when we store posts and not doing thousands at once, I approve.

**Review by tnix100 — APPROVED** [review]

**Comment by tnix100** [comment]
@MikeDev101

**Comment by MikeDev101** [comment]
Merged. Changes will be applied next server maintenance day.

**Pull request merged**
