### PR TITLE
Update profanity_wordlist.txt

### PR DESCRIPTION
**Pull request by roblox888i235**

### CODE REVIEW

**Comment by roblox888i235** [comment]
wtf can be what the frick

**Comment by EngineerRunner** [comment]
you aren't mature enough to be looking at this wordlist

**Comment by mybearworld** [comment]
These are all blocked for very obvious reasons and shouldn't just be removed like that

**Comment by meltland2002** [comment]
p*rnhub is already on the list, the removed ones shouldn't be removed

**Pull request closed without merging**
