### PR TITLE
fix: Make it so users don't know anything about deleted posts or group chats they're not in

### PR DESCRIPTION
**Pull request by tnix100**

### CODE REVIEW

**Review by JoshAtticus — APPROVED** [review]

**Review by MikeDev101 — APPROVED** [review]

**Review by showierdata9978 — APPROVED** [review]

**Comment by showierdata9978** [comment]
looks fine, but made with the github web editor

**Comment by tnix100** [comment]
Ready to deploy @MikeDev101.

**Comment by tnix100** [comment]
> looks fine, but made with the github web editor

lol, how could you tell it was made with the GH web editor?

**Comment by showierdata9978** [comment]
> > looks fine, but made with the github web editor
> 
> lol, how could you tell it was made with the GH web editor?

look at the gpg key used

**Comment by tnix100** [comment]
> > > looks fine, but made with the github web editor
> > 
> > 
> > lol, how could you tell it was made with the GH web editor?
> 
> look at the gpg key used

Oh yeah

**Comment by MikeDev101** [comment]
> Ready to deploy @MikeDev101.

Commit applied.

**Pull request merged**
