### PR TITLE
Feature - Post reactions

### PR DESCRIPTION
**Pull request by NotFenixio**
Adds post reactions. Tested
Changed database version from 6 to 6.1

### CODE REVIEW

**Comment by NotFenixio** [comment]
I completely forgot to send the update lmao, on it

**Comment by NotFenixio** [comment]
[f878d68](https://github.com/meower-media-co/Meower-Server/pull/245/commits/f878d68f338c5d5d090184e39f1367b4cce9d70e) has been tested too

**Review by tnix100 — CHANGES_REQUESTED** [review]
1. The reactions should be separated into another database collection. Having a long list of reactions on the post itself will have performance issues.
2. To follow REST a bit better, it's probably better to have reactions added/removed via PUT | DELETE /posts/<post ID>/reactions/<emoji>.
3. We only use whole numbers for the DB version, so just round it up to 7 rather than 6.1.

**Comment by mybearworld** [comment]
> * The reactions should be separated into another database collection. Having a long list of reactions on the post itself will have performance issues.

That would require making 25 additional requests when loading home for a client, though.

**Comment by tnix100** [comment]
> > * The reactions should be separated into another database collection. Having a long list of reactions on the post itself will have performance issues.
> 
> That would require making 25 additional requests when loading home for a client, though.

No, we'd have a similar thing to Discord, include the count on the message. Just at the DB level have them separated.
image

**Comment by tnix100** [comment]
It's just our current backend kind of sucks so this will be a bit annoying to implement.

**Comment by mybearworld** [comment]
> No, we'd have a similar thing to Discord, include the count on the message. Just at the DB level have them separated.

Ah okay, sorry

**Comment by NotFenixio** [comment]
Since this is going to be in a collection, in order to create the index, we'd need to save reaction times.

**Comment by tnix100** [comment]
> Since this is going to be in a collection, in order to create the index, we'd need to save reaction times.

Why would you need to have a timestamp on the reactions? I'd just store it like `{_id: {post_id: "<post ID>", emoji: "<emoji>", user: "<user>"}}`, with a compound index of `{_id.post_id: 1, _id.emoji: 1}` for fast lookups by post ID and (optionally) emoji. Checking whether a user has reacted with a certain emoji can be done using the default _id index.

**Comment by NotFenixio** [comment]
Should each reaction object on posts include a list of users that reacted with that specific emoji then? Because if we want to also show if the current user reacted with that emoji, we'd need to update all endpoints returning posts to inject that (I've prepared a function in the supporter).

**Comment by NotFenixio** [comment]
Done

**Comment by tnix100** [comment]
Replaced by #247.

**Pull request closed without merging**
