### PR TITLE
fix a bug i noticed (Tokens could be inf long)

### PR DESCRIPTION
**Pull request by showierdata9978**

### CODE REVIEW

**Comment by tnix100** [comment]
Oh yeah, forgot to fix that in my last commit.

**Comment by tnix100** [comment]
Change it to 70 characters

**Comment by showierdata9978** [comment]
@tnix100 done

**Review by tnix100 — APPROVED** [review]

**Comment by showierdata9978** [comment]
@MikeDev101

**Comment by showierdata9978** [comment]
was i suppose to pull this when tnix approved lol?

**Pull request merged**
