### PR TITLE
Post replies

### PR DESCRIPTION
**Pull request by NotFenixio**
Tested

### CODE REVIEW

**Comment by NotFenixio** [comment]
git are you serious rn

**Comment by NotFenixio** [comment]
...Ignore the 3 commits

**Comment by NotFenixio** [comment]
Tested and ready to merge!

**Comment by tnix100** [comment]
Can we change the field on the post to `reply_ids` so it doesn't conflict with `replies` I'm the future when we auto-load them on posts? Keep it as `replies` when making a post though.

**Comment by NotFenixio** [comment]
Done

**Review by tnix100 — APPROVED** [review]

**Comment by tnix100** [comment]
Will merge after post reactions, to not cause DB version conflict.

**Pull request merged**
