### PR TITLE
God forgive me

### PR DESCRIPTION
**Pull request by Bloctans**
adds "Gyatt" and "Gyat" (Both slang for big ass)

### CODE REVIEW

**Comment by theotherhades** [comment]
Not needed, "gyatt" isn't vulgar, at least in my opinion.

**Comment by HAZARD6896** [comment]
I don't believe it's vulgar either. It does mean "butt" but not in a vulgar way

**Comment by showierdata9978** [comment]
wait why is better-profanity not a submodule anymore

**Comment by tnix100** [comment]
Closing as people seem to agree that this word isn't vulgar.

**Pull request closed without merging**
